### ISSUE TITLE
Set GitHub Personal Access Token

### ISSUE THREAD

**Issue by uribo** [nies-consplan/ramora#16]
APIリミットに達してしまうのを防ぐ

**Comment by uribo** [comment]
ARGコマンドを利用する。

## docker

ramoraのみ (検証用)

```
docker build --build-arg GITHUB_PAT=XXXX -t ramora
docker run --rm -e PASSWORD=PASS -p 8787:8787 ramora
```

## docker-compose

各プロジェクト (Dockerfileを拡張させる)

`.env`

```bash
GITHUB_PAT=XXXX
```

`Dockerfile`

```bash
...
ARG GITHUB_PAT

RUN set -x && \
  echo "GITHUB_PAT=$GITHUB_PAT" >> /usr/local/lib/R/etc/Renviron
```

`docker-compose.yml`

```yml
    build:
      context: "."
      args:
        - GITHUB_PAT=${GITHUB_PAT}
```
